Greenter\Model\Sale\SaleDetail:
    properties:
        unidad:
            type: string
        cantidad:
            type: float
        codProducto:
            type: string
        codProdSunat:
            type: string
        codProdGS1:
            type: string
        descripcion:
            type: string
        mtoValorUnitario:
            type: float
        descuento:
            type: float
        igv:
            type: float
        tipAfeIgv:
            type: string
        isc:
            type: float
        tipSisIsc:
            type: string
        totalImpuestos:
            type: float
        icbper:
            type: float
        factorIcbper:
            type: float
        mtoPrecioUnitario:
            type: float
        mtoValorVenta:
            type: float
        mtoValorGratuito:
            type: float
        mtoBaseIgv:
            type: float
        porcentajeIgv:
            type: float
        mtoBaseIsc:
            type: float
        porcentajeIsc:
            type: float
        mtoBaseOth:
            type: float
        porcentajeOth:
            type: float
        otroTributo:
            type: float
        cargos:
            type: array<Greenter\Model\Sale\Charge>
        descuentos:
            type: array<Greenter\Model\Sale\Charge>
        atributos:
            type: array<Greenter\Model\Sale\DetailAttribute>
